version: '3'

volumes:
  postgres_data: {}

services:
  order-payment-gateway:
    image: node:alpine
    user: "node"
    working_dir: /home/node/order-payment-gateway
    environment:
      - NODE_ENV=development
      - SHOPIFY_AUTHENTICATED_STORE_URL=$SHOPIFY_AUTHENTICATED_STORE_URL
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
      - SMARTYSTREETS_AUTH_ID=$SMARTYSTREETS_AUTH_ID
      - SMARTYSTREETS_AUTH_TOKEN=$SMARTYSTREETS_AUTH_TOKEN
      - AVALARA_USERNAME=$AVALARA_USERNAME
      - AVALARA_PASSWORD=$AVALARA_PASSWORD
    ports:
      - "3002:3002"
    volumes:
      - ./order-payment-gateway:/home/node/order-payment-gateway
      - ./order-payment-gateway/node_modules:/home/node/order-payment-gateway/node_modules
    expose:
      - "3002"
    command: [sh, -c, "npm i && ./node_modules/.bin/nodemon app.js"]
  db:
    image: postgres:11
    container_name: opg_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbs_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
